### ISSUE TITLE
Activity Date Comprehensiveness Validation Methodology seems off

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Stats#112]
http://dashboard.iatistandard.org/comprehensiveness_core.html

The `Activity Date` column has a Basic and a Validation Methodology. The Basic Methodology seems OK. The Validation methodology, however, seems off.

Take a couple of AidStream files:

* AECOM https://aidstream.org/files/xml/aecom-activities.xml
* AfriKids https://aidstream.org/files/xml/afrikids-activities.xml

The former scores 100, while the latter scores 0, despite there seemingly being no difference in the data present.

This issue was highlighted by looking at the data by `United Nations Central Emergency Response Fund (CERF)`.

**Comment by andylolz** [comment]
In the example provided, both publishers score 100. So it’s unclear what the issue was here.

**Comment by Ocre42** [comment]
Validation checks against the schema, which appears to be correct, will be closing this issue as it appears it's no longer valid.
