### ISSUE TITLE
test_budget_not_provided.py doesn’t test live code

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Stats#148]
See:
https://github.com/IATI/IATI-Stats/blob/9c480f91dcb6df71e04edc5f34cf4801a2c3257d/stats/tests/test_budget_not_provided.py

The tests don’t appear to touch live code. Instead, I think they test the toy classes at the bottom of the file.

**Comment by Ocre42** [comment]
That's my bad, leftover stuff from my first iterations. I'll try to sort that out alongside my comprehensiveness and forwardlooking changes coming up. Thanks for pointing them out!
