### ISSUE TITLE
Is publisher_has_org_file redundant?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Stats#15]

**Comment by Ocre42** [comment]
It appears to be useful for keeping track of publishers that don't have organisation files: [Dashboard organisations](https://github.com/IATI/IATI-Dashboard/blob/1d74fb4c4976d2bada744cf5983ed163a328fc49/static/templates/organisation.html#L5), [index](https://github.com/IATI/IATI-Dashboard/blob/1d74fb4c4976d2bada744cf5983ed163a328fc49/static/templates/index.html#L115), etc.
There also appears to be no further context to this issue, so I'll be closing it.
