### ISSUE TITLE
A valid fIle format is showing as invalid for SIDA data

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Stats#65]
The [Dashboard](http://dashboard.iatistandard.org/publisher/sida.html#p_codelists reports) reports that Sida data contains a number of invalid FileFormat types.  One of these is in fact an [allowed value](http://iatistandard.org/201/codelists/FileFormat/): `application/vnd.ms-word.document.macroenabled.12` 

The data powering the Dashboard table is [available here](http://dashboard.iatistandard.org/stats/current/aggregated-publisher/sida/codelist_values.json).

The lines from SIDA data (which contain supposedly invalid fileformats) are as follows:

```
<document-link url="http://iati.openaid.se/docs/826305_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/826305_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/495072_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/685013_1_0.docm" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/1216572_1_0.DOCM" format="application/vnd.ms-word.document.macroenabled.12">
    <document-link url="http://iati.openaid.se/docs/1216572_1_0.DOCM" format="application/vnd.ms-word.document.macroenabled.12">
```

This was obtained from downloading all [SIDA data from the Datastore](http://datastore.iatistandard.org/api/1/access/activity.xml?reporting-org=SE-0&stream=True) then running:
`cat sida-data.xml | grep "application/vnd.ms-word.document.macroenabled.12"`

**Comment by Ocre42** [comment]
This issue appears to come from the fact that codelists are case sensitive, and FileFormat codelist has `application/vnd.ms-word.document.macroEnabled.12` instead of SIDA's `application/vnd.ms-word.document.macroenabled.12`. Unless we want to change the codelists so they are not case sensitive, this is something for SIDA to fix in their xml. @amy-silcock could we contact SIDA about this?

**Comment by amy-silcock** [comment]
Codelists are not to be changed. I've contacted SIDA about these errors.
