### ISSUE TITLE
Disbursement/Expenditure Comprehensiveness on the Dashboard - Hierarchy Logic

### ISSUE THREAD

**Issue by rory09** [IATI/IATI-Stats#69]
Disbursement/Expenditure: the Dashboard denominator is possibly wrong: disbursement / expenditure should only be counted and expected on the lowest level hierarchy, as all transactions should be on the lowest level.

Analysis is needed to make sure that this is happening. A flag could possibly be added to signify if a publisher has included transaction details on a higher hierarchy.

See http://dashboard.iatistandard.org/comprehensiveness_financials.html

**Comment by dalepotter** [comment]
Just been catching up on this one. Do we have an example of a publisher who is affected by this issue report?

I've done a spot check with the three publishers (United States, DfID, and Bees Abroad UK) and I cannot find any issue. An example of the workings for the United States data, who have a score of 60% for Transaction - Disbursement or Expenditure in today's [Dashboard](http://dashboard.iatistandard.org/comprehensiveness_financials.html).

![image](https://cloud.githubusercontent.com/assets/8247168/13112495/ce8d60fe-d582-11e5-8176-be9cdf44f3c8.png)

Looking at the raw statistics, they are publishing across three hierarchies, with data for the bottom hierarchy counted for transaction statistics.  Based on the [counts for hierarchy `3`](http://dashboard.iatistandard.org/stats/current/aggregated-publisher/unitedstates/by_hierarchy.json), they have
77540 activities which count under the methodology (i.e. the value for `transaction_spend`) out of a `transaction_spend` denominator of 127564. This is 60.8% when expressed as a percentage. (Note that the dashboard rounds percentages down to the nearest whole integer.

The United States are an example of a publisher who publish transaction disbursements / expenditures at multiple levels (in the case of today's data, hierarchy 1 reports `"transaction_spend": 1647`).

Hope that this helps clarify the situation, do post if there is any publisher data to investigate for this issue.  In terms of adding a flag to signify this, I'll leave @bill-anderson or @iatisupport to advise.

**Comment by iatisupport** [comment]
I can confirm that Disbursements and Expenditure should always be included at the lowest level when using hierarchies

**Comment by dalepotter** [comment]
Just to confirm that a recent refactoring of the logic in has made this easier to check, and I can confirm that Comprehensiveness -> Transaction Disbursements and Expenditure is using a publishers' bottom hierarchy data for assessment. This can be seen in the following lines [29](https://github.com/IATI/IATI-Dashboard/blob/master/comprehensiveness.py#L29), [51-57](https://github.com/IATI/IATI-Dashboard/blob/master/comprehensiveness.py#L51-57), [128-130](https://github.com/IATI/IATI-Dashboard/blob/master/comprehensiveness.py#L128-130) and [145-151](https://github.com/IATI/IATI-Dashboard/blob/master/comprehensiveness.py#L145-151) of the Dashboard's `comprehensiveness.py` script.

With this in mind, I'll close this issue.
